index:
	@find src/ include/ -type f -name '*.[ch]' > cscope.files
	@find /usr/include/SDL2/ -type f -name '*.[ch]' >> cscope.files
	@cscope -b -q
	@ctags -L cscope.files
	@-rm -f cscope.files

clean-index:
	@-rm -f cscope.out cscope.in.out cscope.po.out tags

.PHONY: index clean-index
